// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {proto} from '../models';
import {bridge} from '../models';

export function ClearRecords():Promise<void>;

export function ClearRecordsBefore(arg1:number):Promise<number>;

export function ClearTraffic():Promise<void>;

export function GetCACertPath():Promise<string>;

export function GetGatewayLogs(arg1:number,arg2:Array<number>):Promise<Array<proto.GatewayLog>>;

export function GetModels():Promise<Array<bridge.ModelInfo>>;

export function GetRecords(arg1:number,arg2:Array<number>):Promise<Array<proto.Record>>;

export function GetStatus():Promise<Record<string, any>>;

export function OpenExternal(arg1:string):Promise<void>;

export function RecentRecords(arg1:number):Promise<Array<proto.Record>>;

export function SetLogging(arg1:boolean):Promise<void>;

export function StartGateway(arg1:number):Promise<void>;

export function StartProxy(arg1:number):Promise<void>;

export function Stats():Promise<any>;

export function StopGateway():Promise<void>;

export function StopProxy():Promise<void>;
