// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearRecords() {
  return window['go']['main']['App']['ClearRecords']();
}

export function ClearRecordsBefore(arg1) {
  return window['go']['main']['App']['ClearRecordsBefore'](arg1);
}

export function ClearTraffic() {
  return window['go']['main']['App']['ClearTraffic']();
}

export function GetCACertPath() {
  return window['go']['main']['App']['GetCACertPath']();
}

export function GetGatewayLogs(arg1, arg2) {
  return window['go']['main']['App']['GetGatewayLogs'](arg1, arg2);
}

export function GetModels() {
  return window['go']['main']['App']['GetModels']();
}

export function GetRecords(arg1, arg2) {
  return window['go']['main']['App']['GetRecords'](arg1, arg2);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function RecentRecords(arg1) {
  return window['go']['main']['App']['RecentRecords'](arg1);
}

export function SetLogging(arg1) {
  return window['go']['main']['App']['SetLogging'](arg1);
}

export function StartGateway(arg1) {
  return window['go']['main']['App']['StartGateway'](arg1);
}

export function StartProxy(arg1) {
  return window['go']['main']['App']['StartProxy'](arg1);
}

export function Stats() {
  return window['go']['main']['App']['Stats']();
}

export function StopGateway() {
  return window['go']['main']['App']['StopGateway']();
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}
