// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelOAuthLogin() {
  return window['go']['main']['App']['CancelOAuthLogin']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ClearGatewayLogs() {
  return window['go']['main']['App']['ClearGatewayLogs']();
}

export function ClearProxyRecords() {
  return window['go']['main']['App']['ClearProxyRecords']();
}

export function ClearRecords() {
  return window['go']['main']['App']['ClearRecords']();
}

export function ClearRecordsBefore(arg1) {
  return window['go']['main']['App']['ClearRecordsBefore'](arg1);
}

export function ClearTraffic() {
  return window['go']['main']['App']['ClearTraffic']();
}

export function GetAnthropicMapping() {
  return window['go']['main']['App']['GetAnthropicMapping']();
}

export function GetCACertPath() {
  return window['go']['main']['App']['GetCACertPath']();
}

export function GetGatewayAPIKey() {
  return window['go']['main']['App']['GetGatewayAPIKey']();
}

export function GetGatewayLogs(arg1, arg2) {
  return window['go']['main']['App']['GetGatewayLogs'](arg1, arg2);
}

export function GetGatewayStats(arg1, arg2) {
  return window['go']['main']['App']['GetGatewayStats'](arg1, arg2);
}

export function GetModels() {
  return window['go']['main']['App']['GetModels']();
}

export function GetNetworkInterfaces() {
  return window['go']['main']['App']['GetNetworkInterfaces']();
}

export function GetRecordBody(arg1) {
  return window['go']['main']['App']['GetRecordBody'](arg1);
}

export function GetRecordBodyByKey(arg1, arg2) {
  return window['go']['main']['App']['GetRecordBodyByKey'](arg1, arg2);
}

export function GetRecordBodyDecoded(arg1) {
  return window['go']['main']['App']['GetRecordBodyDecoded'](arg1);
}

export function GetRecordBodyDecodedByKey(arg1, arg2) {
  return window['go']['main']['App']['GetRecordBodyDecodedByKey'](arg1, arg2);
}

export function GetRecords(arg1, arg2) {
  return window['go']['main']['App']['GetRecords'](arg1, arg2);
}

export function GetRecordsByType(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetRecordsByType'](arg1, arg2, arg3);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function LogError(arg1) {
  return window['go']['main']['App']['LogError'](arg1);
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function RecentRecords(arg1) {
  return window['go']['main']['App']['RecentRecords'](arg1);
}

export function RevealCACert() {
  return window['go']['main']['App']['RevealCACert']();
}

export function RotateGatewayAPIKey() {
  return window['go']['main']['App']['RotateGatewayAPIKey']();
}

export function SaveAnthropicMapping(arg1, arg2) {
  return window['go']['main']['App']['SaveAnthropicMapping'](arg1, arg2);
}

export function SetLingmaHTTP2(arg1) {
  return window['go']['main']['App']['SetLingmaHTTP2'](arg1);
}

export function SetLogging(arg1) {
  return window['go']['main']['App']['SetLogging'](arg1);
}

export function SetProxyLogging(arg1) {
  return window['go']['main']['App']['SetProxyLogging'](arg1);
}

export function StartGateway(arg1, arg2) {
  return window['go']['main']['App']['StartGateway'](arg1, arg2);
}

export function StartOAuthLogin() {
  return window['go']['main']['App']['StartOAuthLogin']();
}

export function StartProxy(arg1) {
  return window['go']['main']['App']['StartProxy'](arg1);
}

export function Stats() {
  return window['go']['main']['App']['Stats']();
}

export function StopGateway() {
  return window['go']['main']['App']['StopGateway']();
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}
