// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {proto} from '../models';
import {bridge} from '../models';

export function ClearGatewayLogs():Promise<void>;

export function ClearProxyRecords():Promise<void>;

export function ClearRecords():Promise<void>;

export function ClearRecordsBefore(arg1:number):Promise<number>;

export function ClearTraffic():Promise<void>;

export function GetAnthropicMapping():Promise<Record<string, any>>;

export function GetCACertPath():Promise<string>;

export function GetGatewayLogs(arg1:number,arg2:number):Promise<Array<proto.GatewayLog>>;

export function GetGatewayStats(arg1:string,arg2:string):Promise<proto.GatewayLogStats>;

export function GetModels():Promise<Array<bridge.ModelInfo>>;

export function GetNetworkInterfaces():Promise<Array<Record<string, string>>>;

export function GetRecords(arg1:number,arg2:number):Promise<Array<proto.Record>>;

export function GetRecordsByType(arg1:number,arg2:number,arg3:string):Promise<Array<proto.Record>>;

export function GetStatus():Promise<Record<string, any>>;

export function GetVersion():Promise<string>;

export function LogError(arg1:string):Promise<void>;

export function OpenExternal(arg1:string):Promise<void>;

export function RecentRecords(arg1:number):Promise<Array<proto.Record>>;

export function RevealCACert():Promise<void>;

export function SaveAnthropicMapping(arg1:Record<string, string>,arg2:string):Promise<void>;

export function SetLogging(arg1:boolean):Promise<void>;

export function SetProxyLogging(arg1:boolean):Promise<void>;

export function StartGateway(arg1:number,arg2:string):Promise<void>;

export function StartOAuthLogin():Promise<void>;

export function StartProxy(arg1:number):Promise<void>;

export function Stats():Promise<any>;

export function StopGateway():Promise<void>;

export function StopProxy():Promise<void>;
